<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

// Migrate to symfony command

$root = __DIR__ . '/test';
$buildDir = __DIR__ . '/build';

$files = \Symfony\Component\Finder\Finder::create()
    ->files()
    ->name('*.php')
    ->in($root)
    ->getIterator();

$parser = new \PhpParser\ParserFactory()->createForNewestSupportedVersion();
$collector = new \Vojtechrichter\StaticPhpDepCompiler\DependencyCollector();
$traverser = new \PhpParser\NodeTraverser();
$traverser->addVisitor($collector);

$fileGraph = [];
$declared = [];

foreach ($files as $file) {
    $realPath = $file->getRealPath();
    $code = file_get_contents($realPath);

    if (str_contains($code, '// This file is auto-generated by Composer')) {
        continue;
    }

    try {
        $ast = $parser->parse($code);
        $collector->setCurrentFile($realPath);
        $traverser->traverse($ast);

        $fileGraph[$realPath] = array_unique($collector->getDependencies()[$realPath] ?? []);
        $declared[$realPath] = $collector->getDeclared()[$realPath] ?? [];
    } catch (Throwable $e) {
        echo sprintf('Parse error in %s - skipping\n', $realPath);
    }
}

$provider = [];
foreach ($declared as $file => $classes) {
    foreach ($classes as $class) {
        $provider[$class] = $file;
    }
}

foreach ($fileGraph as $file => $deps) {
    $realDeps = [];
    foreach ($deps as $dep) {
        if (isset($provider[$dep])) {
            $realDeps[] = $provider[$dep];
        }
    }
    $fileGraph[$file] = array_unique($realDeps);
}

$inDegree = array_fill_keys(array_keys($fileGraph), 0);
foreach ($fileGraph as $deps) {
    foreach ($deps as $dep) {
        $inDegree[$dep] ??= 0;
        $inDegree[$dep]++;
    }
}

$queue = array_keys(array_filter($inDegree, fn($d) => $d === 0));
$sorted = [];

while ($queue) {
    $file = array_shift($queue);
    $sorted[] = $file;

    foreach ($fileGraph[$file] ?? [] as $dep) {
        $inDegree[$dep]--;
        if ($inDegree[$dep] === 0) {
            $queue[] = $dep;
        }
    }
}

foreach (array_keys($fileGraph) as $file) {
    if (!in_array($file, $sorted, true)) {
        $sorted[] = $file;
    }
}

$preloadPath = $buildDir . '/static-preload.php';
$bootstrapPath = $buildDir . '/static-bootstrap.php';

file_put_contents($bootstrapPath, <<<PHP
<?php
// static-bootstrap.php - Generated

declare(strict_types=1);

ini_set('opcache.enable', '1');
ini_set('opcache.jit_buffer_size', '256M');
ini_set('opcache.jit', '1255');
ini_set('opcache.validate_timestamps', '0');
ini_set('opcache.save_comments', '1'); // Necessary for attributes

opcache_preload(__DIR__ . '/static-preload.php');
PHP
);

$preload = '<?php\n// static-preload.php - Generated on ' . date('Y-m-d H:i:s') . '\n\n';
foreach ($sorted as $i => $file) {
    $relative = str_replace($root . '/', '', $file);
    $content = file_get_contents($file);
    if (str_starts_with(trim($content), '<?php')) {
        $content = substr($content, strpos($content, '<?php') + 5);
    }

    $preload .= '// ' . sprintf('%05d', $i + 1) . ' - ' . $relative . '\n';
    $preload .= $content . '\n\n';
}

file_put_contents($preloadPath, $preload);
