<?php

declare(strict_types=1);

namespace Photon;

use Photon\Dependencies\DependencyVisitor;
use Photon\Generators\BootstrapGenerator;
use Photon\Generators\PreloadGenerator;
use Symfony\Component\Finder\Finder;

final class Kernel
{
    private const string BootstrapFileName = 'photon-bootstrap';

    private const string PreloadFileName = 'photon-preload';

    private ?Finder $finder = null;

    private ?string $buildDir = null;

    public static function create(): self
    {
        return new self();
    }

    public function fromDirs(array $dirs): self
    {
        $this->finder = Finder::create()
            ->files()
            ->name('*.php')
            ->in($dirs);

        return $this;
    }

    public function buildDir(string $dir): self
    {
        if (!is_dir($dir) && !mkdir($dir) && !is_dir($dir)) {
            throw new \RuntimeException(sprintf('Directory "%s" could not be created.', $dir));
        }

        $this->buildDir = $dir;

        return $this;
    }

    public function boot(): void
    {
        if ($this->finder === null) {
            throw new \RuntimeException('No directories were set for scanning, use the Kernel::fromDirs method.');
        }

        if ($this->buildDir === null) {
            throw new \RuntimeException('Build dir not set.');
        }

        $files = $this->finder->getIterator();

        $parser = new \PhpParser\ParserFactory()->createForNewestSupportedVersion();
        $depVisitor = new DependencyVisitor();

        $traverser = new \PhpParser\NodeTraverser($depVisitor);

        $fileGraph = [];
        $declared = [];

        foreach ($files as $file) {
            $realPath = $file->getRealPath();
            $code = file_get_contents($realPath);

            if (str_contains($code, '// This file is auto-generated by Composer')) {
                continue;
            }

            try {
                $ast = $parser->parse($code);
                $depVisitor->setCurrentFile($realPath);
                $traverser->traverse($ast);

                $fileGraph[$realPath] = array_unique($depVisitor->getDependencies()[$realPath] ?? []);
                $declared[$realPath] = $depVisitor->getDeclared()[$realPath] ?? [];
            } catch (\Throwable) {
                echo sprintf('Parse error in %s - skipping\n', $realPath);
            }
        }

        $provider = [];
        foreach ($declared as $file => $classes) {
            foreach ($classes as $class) {
                $provider[$class] = $file;
            }
        }

        foreach ($fileGraph as $file => $deps) {
            $realDeps = [];
            foreach ($deps as $dep) {
                if (isset($provider[$dep])) {
                    $realDeps[] = $provider[$dep];
                }
            }
            $fileGraph[$file] = array_unique($realDeps);
        }

        $inDegree = array_fill_keys(array_keys($fileGraph), 0);
        foreach ($fileGraph as $deps) {
            foreach ($deps as $dep) {
                $inDegree[$dep] ??= 0;
                $inDegree[$dep]++;
            }
        }

        $queue = array_keys(array_filter($inDegree, fn($d) => $d === 0));
        $sorted = [];

        while ($queue) {
            $file = array_shift($queue);
            $sorted[] = $file;

            foreach ($fileGraph[$file] ?? [] as $dep) {
                $inDegree[$dep]--;
                if ($inDegree[$dep] === 0) {
                    $queue[] = $dep;
                }
            }
        }

        foreach (array_keys($fileGraph) as $file) {
            if (!in_array($file, $sorted, true)) {
                $sorted[] = $file;
            }
        }

        $preloadFile = $this->buildDir . sprintf('/%s.php', self::PreloadFileName);
        $bootstrapFile = $this->buildDir . sprintf('/%s.php', self::BootstrapFileName);

        BootstrapGenerator::printTo($bootstrapFile);

        $preload = "<?php\n// static-preload.php - Generated on " . date('Y-m-d H:i:s') . "\n\n";

        foreach ($sorted as $i => $file) {
            $content = file_get_contents($file);
            if (str_starts_with(trim($content), '<?php')) {
                $content = substr($content, strpos($content, '<?php') + 5);
            }

            $preload .= '// ' . sprintf('%05d', $i + 1) . ' - ' . $file . "\n";
            $preload .= $content . "\n\n";
        }

        PreloadGenerator::printTo($preloadFile, $preload);
    }
}
